build:
    environment:
        php: '5.4.28'
        mongodb: true
    dependencies:
        override:
            - 'ls'
    tests:
        override:
            - 'ls'

tools:
    php_sim: true
    php_changetracking: true
    php_cs_fixer:
        config: { level: psr2 }
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: false
    sensiolabs_security_checker: true
    external_code_coverage: true
